### PR TITLE
Dynamically create the service_conf.yaml file by replacing environment variables from .env

### PR DESCRIPTION
**Pull request by gschmutz**
### What problem does this PR solve?

This pull request implements the feature mentioned in #3322. 

Instead of manually having to edit the `service_conf.yaml` file when changes have been made to `.env` and mapping it into the docker container at runtime, a template file is used and the values replaced by the environment variables from the `.env` file when the container is started.
 

### Type of change

- [X] New Feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by writinwaters — APPROVED** [review]
Graceful indeed. Many thanks!

**Comment by writinwaters** [comment]
Also, thanks for the painstaking edits to the README and docs!

**Comment by yuzhichang** [comment]
The CI is blocked due to unable to connect to ragflow-server. Need to investigate why.

**Comment by yuzhichang** [comment]
Fixed code to pass CI.
Welcome contribution!

**Comment by gschmutz** [comment]
@yuzhichang thanks for fixing it, pretty sure it worked when I tested it a few days ago. But I like it better if it is done all in the `conf` folder.

**Pull request merged**
