### PR TITLE
Add Architecture-Specific Logic for msodbcsql in Dockerfile #4036

### PR DESCRIPTION
**Pull request by midilandlu**
### What problem does this PR solve?

For the new feature Add mssql support in the Dockerfile, I suggest including support for msodbcsql18 for ARM64.
Based on current testing results (on macOS ARM64 environment), msodbcsql18 needs to be installed.
I hope future Dockerfiles can incorporate a conditional check for this. Specifically:

When $ARCH=arm64 (macOS ARM64 environment), install msodbcsql18.
In other cases (general x86_64 environment), install msodbcsql17.
### Type of change

- [x] New Feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by hsoftxl** [comment]
没有ARCH变量， macos 执行异常

修正后：

# 获取系统架构并设置 ARCH 变量
RUN ARCH=$(dpkg --print-architecture) && \
    echo "Architecture is: $ARCH" && \
    
    # 添加 Microsoft ODBC 驱动程序的源
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    
    apt update && \
    
    # 根据系统架构选择安装 ODBC 驱动程序
    if [ "$ARCH" = "arm64" ]; then \
        # ARM64 (如 MacOS ARM 架构)
        ACCEPT_EULA=Y apt install -y unixodbc-dev msodbcsql18; \
    else \
        # x86_64 (如一般的 x86 架构)
        ACCEPT_EULA=Y apt install -y unixodbc-dev msodbcsql17; \
    fi || \
    { echo "Failed to install ODBC driver"; exit 1; }

**Comment by hsoftxl** [comment]
@midilandlu

**Comment by midilandlu** [comment]
@hsoftxl 

Tonight, I pulled the nightly image to build RAG v0.14.1-172-g79e435fc slim, but encountered the following error during the image build process. I would like to confirm with the team whether the current version of the Dockerfile can successfully build a Docker image on macOS.

Eventually, I reverted to the Dockerfile version I submitted yesterday and was only able to successfully build the Docker image on macOS using the Solution 1 command.

Failed Docker Build Commands:
Solution 1:

```
docker build \
--build-arg ARCH=arm64 \
--build-arg LIGHTEN=1 \
-f Dockerfile \
-t my-ragflow:nightly-slim \
.
```

Solution 2:

```
docker build \
--build-arg LIGHTEN=1 \
-f Dockerfile \
-t my-ragflow:nightly-slim \
.
```

Error Message:
```
Dockerfile:92
--------------------
  91 |     # general x86_64 environment, install msodbcsql17.
  92 | >>> RUN --mount=type=cache,id=ragflow_apt,target=/var/cache/apt,sharing=locked \
  93 | >>>     curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
  94 | >>>     curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
  95 | >>>     apt update && \
  96 | >>>     if [ -n "$ARCH" ] && [ "$ARCH" = "arm64" ]; then \
  97 | >>>         # MacOS ARM64 
  98 | >>>         ACCEPT_EULA=Y apt install -y unixodbc-dev msodbcsql18; \
  99 | >>>     else \
 100 | >>>         # (x86_64)
 101 | >>>         ACCEPT_EULA=Y apt install -y unixodbc-dev msodbcsql17; \
 102 | >>>     fi || \
 103 | >>>     { echo "Failed to install ODBC driver"; exit 1; }
 104 |     
--------------------
ERROR: failed to solve: process "/bin/bash -c curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - &&     curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list &&     apt update &&     if [ -n \"$ARCH\" ] && [ \"$ARCH\" = \"arm64\" ]; then         ACCEPT_EULA=Y apt install -y unixodbc-dev msodbcsql18;     else         ACCEPT_EULA=Y apt install -y unixodbc-dev msodbcsql17;     fi ||     { echo \"Failed to install ODBC driver\"; exit 1; }" did not complete successfully: exit code: 1
```

**Comment by hsoftxl** [comment]
我的设备是 Mac Studio ultra , 使用你PR 的脚本，会报错。   但是我发的脚本能正常运行  @midilandlu

**Comment by midilandlu** [comment]
@hsoftxl 
May I ask if the command you used to build the image is: 
docker build --build-arg LIGHTEN=1 -f Dockerfile -t infiniflow/ragflow:nightly-slim .

**Comment by southkorea2013** [comment]
@midilandlu I cannot run the following command on macOS:
docker build --build-arg ARCH=arm64 --build-arg LIGHTEN=1  -f Dockerfile -t infiniflow/ragflow:v0.14.1-slim .
Thanks.

**Comment by southkorea2013** [comment]
The first issue is the same as hsoftxl,  I manually add the following settings before your codes to work around the issue.
ENV ARCH=arm64

**Comment by hsoftxl** [comment]
@midilandlu  < docker build .      >  , i use this command

**Pull request merged**
