### PR TITLE
Updated deploy a local llm using IPEX-LLM

### PR DESCRIPTION
**Pull request by writinwaters**
### Type of change

- [x] Documentation Update

### CODE REVIEW

**Comment by writinwaters** [comment]
Hi, @lzivan massive editorial changes made to this document. Could I ask you to double check if I have altered the intended meaning?

**Comment by lzivan** [comment]
Sure, I'll have a check on that.

**Comment by lzivan** [comment]
Hi @writinwaters , the contents are fine. But I'm not sure whether it's a format issue caused by Github?
image

**Comment by writinwaters** [comment]
No. Files under docs will be synchronized to the ragflow-docs repo and and organized into our doc site by Docusaurus 3. The tags you see will become tabs in our doc site. Example here: https://ragflow.io/docs/dev/#start-up-the-server

**Comment by lzivan** [comment]
Got it. No problem on my end.

**Comment by writinwaters** [comment]
Thanks @lzivan for the proofread!

**Pull request merged**
