### PR TITLE
The default max tokens of 215 is too small, answers are often cut off.I will modify it to 512 to address this issue.

### PR DESCRIPTION
**Pull request by dashi6174**
### What problem does this PR solve?

_Briefly describe what this PR aims to solve. Include background context that will help reviewers understand the purpose of the PR._

### Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

### CODE REVIEW

**Comment by writinwaters** [comment]
I can relate and I think this makes sense! @KevinHuSh

**Comment by sliontc** [comment]
How about in agent section? The agent also cuts off the answers.

**Comment by KevinHuSh** [comment]
image

**Comment by sliontc** [comment]
thanks a lot.

**Comment by martinarisk** [comment]
0.17.2 bedrock doesn't have Max tokens in agent: 
image

**Comment by writinwaters** [comment]
Yes, you are right. https://ragflow.io/docs/dev/release_notes#v0172

**Pull request merged**
