### PR TITLE
Theme switch support

### PR DESCRIPTION
**Pull request by isthaison**
### What problem does this PR solve?
- [x] New Feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by cike8899** [comment]
There are many display issues in night mode, such as

image

**Comment by isthaison** [comment]
image
 I 've update for flow. @cike8899 , please check again

**Comment by isthaison** [comment]
hi @cike8899 . In this project css declaration is separate, it is difficult to check all ui components. Can you check again, thank you

**Comment by cike8899** [comment]
image
image
image
image
image
image
image
image

**Comment by isthaison** [comment]
@cike8899  please check again

**Comment by isthaison** [comment]
cc @yingfeng

**Comment by isthaison** [comment]
@cike8899  please check again

**Comment by cike8899** [comment]
image
image

**Comment by isthaison** [comment]
Hi @cike8899. Please check again. Hope it will be ok

**Comment by cike8899** [comment]
image
image

**Comment by isthaison** [comment]
Hi @cike8899, Let's continue

**Comment by cike8899** [comment]
image
image
image

**Comment by isthaison** [comment]
image
if it drags on it will never end because of the updates

**Comment by JinHai-CN** [comment]
I resolve the conflicts, you might need to pull the latest version @isthaison

**Comment by isthaison** [comment]
@JinHai-CN  I got it

**Comment by cike8899** [comment]
image
image
image

**Comment by JinHai-CN** [comment]
@isthaison more conflicts need to resolve

**Comment by isthaison** [comment]
I think there should be Icon processing to be able to deeply customize color and size instead of importing directly from svg file, this is quite inconvenient. in this commit request. I have a solution for it, you can refer to it to implement for the next features. @cike8899

**Comment by cike8899** [comment]
Adjust the card style in the agent to make it the same as the cards in the knowledge base

image

image

**Comment by cike8899** [comment]
image

1. Switch to the dark theme
2. Click on other pages, such as the agent page
3. Switch to the day theme
4. Click on the Retrieval testing page
5. Found that sometimes the form will have a black background

**Comment by isthaison** [comment]
@cike8899  please check again

**Comment by cike8899** [comment]
image
image

**Comment by isthaison** [comment]
@cike8899  @yingfeng , please check  again

**Review by yingfeng — CHANGES_REQUESTED** [review]
Please guarantee it can pass the CI before it could be merged. 
Why you downgrade duckduckgo-search in poetry?

**Comment by isthaison** [comment]
image
with current version duckgo has rate limited problem. this is related issue
relate Is: https://github.com/crewAIInc/crewAI/issues/136

**Comment by isthaison** [comment]
If so I will split it into 2 requests. That will be more convenient.

**Review by yingfeng — APPROVED** [review]

**Pull request merged**
