### PR TITLE
feat: support xinference rerank model

### PR DESCRIPTION
**Pull request by hwzhuhao**
### What problem does this PR solve?

support xinference rerank model
#1455 

### Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

### CODE REVIEW

**Comment by jay-jjwu** [comment]
what is the base url for rerank model of xinference?

**Comment by jay-jjwu** [comment]
> what is the base url for rerank model of xinference?

There is always an error "Fail to access model(bge-reranker-v2-m3).'results'", any ideas?
The xinference API works well, because i tested with postman.
BTW, the embedding models work well too.
What's wrong with the rerank models?

**Comment by morler** [comment]
You need to add a **rerank** directory to the address, like this: **http://host:port/v1/rerank**.

**Comment by chinamerp** [comment]
> You need to add a **rerank** directory to the address, like this: **http://host:port/v1/rerank**.

it not works at xinference:v0.15.3

**Pull request merged**
