### PR TITLE
add password reset function by extending the Flask command

### PR DESCRIPTION
**Pull request by hwzhuhao**
### What problem does this PR solve?
add password reset function by extending the Flask command. #1200 

### Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

### CODE REVIEW

**Comment by hwzhuhao** [comment]
(ragflow) root@gpu-86-41:/opt/ragflow# export FLASK_APP=api.apps
(ragflow) root@gpu-86-41:/opt/ragflow# flask --help
Usage: flask [OPTIONS] COMMAND [ARGS]...

  A general utility script for Flask applications.

  An application to load must be given with the '--app' option, 'FLASK_APP'
  environment variable, or with a 'wsgi.py' or 'app.py' file in the current
  directory.

Options:
  -e, --env-file FILE   Load environment variables from this file. python-
                        dotenv must be installed.
  -A, --app IMPORT      The Flask application or factory function to load, in
                        the form 'module:name'. Module can be a dotted import
                        or file path. Name is not required if it is 'app',
                        'application', 'create_app', or 'make_app', and can be
                        'name(args)' to pass arguments.
  --debug / --no-debug  Set debug mode.
  --version             Show the Flask version.
  --help                Show this message and exit.

Commands:
  reset-password  Reset the account password.
  routes          Show the routes for the app.
  run             Run a development server.
  shell           Run a shell in the app context.

(ragflow) root@gpu-86-41:/opt/ragflow# flask reset-password --email gtawu12138@gmail.com --new-password admin123 --password-confirm admin123

Congratulations! Password has been reset.

**Comment by KevinHuSh** [comment]
> (ragflow) root@gpu-86-41:/opt/ragflow# export FLASK_APP=api.apps (ragflow) root@gpu-86-41:/opt/ragflow# flask --help Usage: flask [OPTIONS] COMMAND [ARGS]...
> 
> A general utility script for Flask applications.
> 
> An application to load must be given with the '--app' option, 'FLASK_APP' environment variable, or with a 'wsgi.py' or 'app.py' file in the current directory.
> 
> Options: -e, --env-file FILE Load environment variables from this file. python- dotenv must be installed. -A, --app IMPORT The Flask application or factory function to load, in the form 'module:name'. Module can be a dotted import or file path. Name is not required if it is 'app', 'application', 'create_app', or 'make_app', and can be 'name(args)' to pass arguments. --debug / --no-debug Set debug mode. --version Show the Flask version. --help Show this message and exit.
> 
> Commands: reset-password Reset the account password. routes Show the routes for the app. run Run a development server. shell Run a shell in the app context.
> 
> (ragflow) root@gpu-86-41:/opt/ragflow# flask reset-password --email [gtawu12138@gmail.com](mailto:gtawu12138@gmail.com) --new-password admin123 --password-confirm admin123
> 
> Congratulations! Password has been reset.

This new password is effective for login with web UI, isn't it? 
But I'm wondering about whether the encryption/decryption would cause issue about this new password.

**Comment by hwzhuhao** [comment]
yes, the new password is effective for login with web UI

**Comment by hwzhuhao** [comment]
This password has already been stored in the database, so it won't affect encryption/decryption. According to the user registration implementation logic, the current database only stores the Base64 encoded hash value.

**Comment by KevinHuSh** [comment]
> This password has already been stored in the database, so it won't affect encryption/decryption. According to the user registration implementation logic, the current database only stores the Base64 encoded hash value.

By the historical reason, the current procedure is :

--------Front end------------- |-------------backend------------
pwd -> base64 -> encrypt ->| base64->decrypt->store in DB.

So, for now, if a reset password can be passed through web UI, it should go throngh this procedure.

**Comment by hwzhuhao** [comment]
So ragflow will add the functionalities for users to reset passwords and recover forgotten passwords in the web UI?

**Comment by hwzhuhao** [comment]
I think this can also be used by backend administrators to directly reset passwords through the command line.

**Pull request merged**
