### PR TITLE
feat: FastEmbed embedding support

### PR DESCRIPTION
**Pull request by Anush008**
### Description

Following up on https://github.com/infiniflow/ragflow/pull/275, this PR adds support for FastEmbed model configurations.

The options are not exhaustive. You can find the full list [here](https://qdrant.github.io/fastembed/examples/Supported_Models/). 

P.S. I ran into OOM issues when building the image.

### Type of change

- [x] New Feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by KevinHuSh** [comment]
Impressive. 
Applied your PR. But I still can't choose it from the web interface.
Could you refine this?

Thanks for your contribution.

**Comment by KevinHuSh** [comment]
Impressive. 
Applied your PR. But I still can't choose it from the web interface.
Could you refine this?

Thanks for your contribution.

**Comment by Anush008** [comment]
Hi @KevinHuSh, could you reopen the PR so that I can changes to the same? Instead of opening a new one.

**Comment by KevinHuSh** [comment]
> Hi @KevinHuSh, could you reopen the PR so that I can changes to the same? Instead of opening a new one.

Sorry, mistaken operation!

**Pull request merged**
