### PR TITLE
Web: Fixed the download and preview file not authorized.

### PR DESCRIPTION
**Pull request by baifachuan**
https://github.com/infiniflow/ragflow/issues/3651

### What problem does this PR solve?

_Briefly describe what this PR aims to solve. Include background context that will help reviewers understand the purpose of the PR._

### Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by baifachuan** [comment]
image


download file or preview use the '/get/<file_id>'  API, but the API is not authorized.

so you can call the api to download file with anonymous user.

This is a very big security risk.

download or preview file must be login user, not anonymous user.

**Comment by baifachuan** [comment]
But I have another question, why only link file to KB can download or preview?

If the file not link to KB, you can get this error:

image

Why?

**Comment by yuzhichang** [comment]
@baifachuan Could you fix the conflict?

**Comment by baifachuan** [comment]
@yuzhichang Done

**Pull request merged**
