### PR TITLE
Add support for VolcEngine - the current version supports SDK2

### PR DESCRIPTION
**Pull request by yungongzi**
- The main idea is to assemble **ak**, **sk**, and **ep_id** into a dictionary and store it in the database **api_key** field
- I don’t know much about the front-end, so I learned from Ollama, which may be redundant.

### Configuration method

- model name

- Format requirements: {"VolcEngine model name":"endpoint_id"}
    - For example: {"Skylark-pro-32K":"ep-xxxxxxxxx"}
    
- Volcano ACCESS_KEY
    - Format requirements: VOLC_ACCESSKEY of the volcano engine corresponding to the model

- Volcano SECRET_KEY
    - Format requirements: VOLC_SECRETKEY of the volcano engine corresponding to the model
    
image

### What problem does this PR solve?

_Briefly describe what this PR aims to solve. Include background context that will help reviewers understand the purpose of the PR._

### Type of change

- [x] New Feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by JinHai-CN** [comment]
We intend to create an international community, so we encourage using English for issues and pull requests.  Would you please update the PR description and the code comments ?

**Review by KevinHuSh — APPROVED** [review]

**Review by cike8899 — APPROVED** [review]
well done

**Comment by dongjiashi** [comment]
Dear @yungongzi and all,

Since VolcEngine's latest model(Doubao series) and SDK v3 has been published for quiet a while, may I know if you considerate to make a new feature to support that?

AFAIK, the v3 SDK supports API_KEY, and the LLMs are named as Doubao-[pro|lite]-[4k|32k|128k].
Supporting this really helps.

Your sincerely.

**Comment by yungongzi** [comment]
> Dear @yungongzi and all,
> 
> Since VolcEngine's latest model(Doubao series) and SDK v3 has been published for quiet a while, may I know if you considerate to make a new feature to support that?
> 
> AFAIK, the v3 SDK supports API_KEY, and the LLMs are named as Doubao-[pro|lite]-[4k|32k|128k]. Supporting this really helps.
> 
> Your sincerely.

Ok, I'll try my best to finish.
However, the model name of VolcEngine v3 is still the EndpointID corresponding to different models, and the model name cannot be used directly【Doubao-[pro|lite]-[4k|32k|128k]】.
借虎先锋一句话：马了个巴子，这都V3改了一半儿啊！

**Comment by dongjiashi** [comment]
> Ok, I'll try my best to finish. However, the model name of VolcEngine v3 is still the EndpointID corresponding to different models, and the model name cannot be used directly【Doubao-[pro|lite]-[4k|32k|128k]】. 借虎先锋一句话：马了个巴子，这都V3改了一半儿啊！

Great! And thank you very much for your contribution!

**Pull request merged**
