### PR TITLE
Feature/component deploy

### PR DESCRIPTION
**Pull request by chongchuanbing**
### What problem does this PR solve?

1. feat: split ```ragflow``` into three components(```ragflow-web```, ```ragflow-api```, ```ragflow-worker```)

### Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

### CODE REVIEW

**Comment by KevinHuSh** [comment]
Appreciate your contribution.

Feature 2 involves a scope that is too broad and makes changes to the entire framework, so it will not be adopted for the time being.

**Comment by yuzhichang** [comment]
@chongchuanbing Please split feature 2 into another PR. I'm considering replacing nginx with uvicorn, or even converting the codebase to async style.

**Comment by chongchuanbing** [comment]
> @chongchuanbing Please split feature 2 into another PR. I'm considering replacing nginx with uvicorn, or even converting the codebase to async style.

I have removed the bug fix, now only feature 2.

**Comment by yuzhichang** [comment]
@chongchuanbing I would suggest:
- Remove Nginix entirely. We don't want to maintain such complex configuration. You could split that into another repo.
- Merge `ragflow-web` and `ragflow-api` into one. An single flask serves API and static pages.
- Introduce [Gunicorn](https://flask.palletsprojects.com/en/2.3.x/deploying/gunicorn/) so that ragflow-server runs in thread-pool.
- Research replacing Flask with Quart(https://github.com/pallets/quart), the async variant of Flask.

**Pull request closed without merging**
