### PR TITLE
Fix agent api invokation issue

### PR DESCRIPTION
**Pull request by KevinHuSh**
### What problem does this PR solve?

#3570 

### Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by peizimo** [comment]
How long will it take to fix it, can you teach us how to deal with it, or do we need to wait until the upgrade

**Comment by peizimo** [comment]
sorry ,  I have got , thanks

**Comment by Yinst0** [comment]
I encountered a problem when running the same code as #3570. May I ask how to solve this problem? My problem is as follows:
Traceback (most recent call last):
  File "/workspace/myragflow/test.py", line 15, in <module>
    for ans in session.ask(question, stream=True):
  File "/root/anaconda3/envs/ragflow/lib/python3.12/site-packages/ragflow_sdk/modules/session.py", line 34, in ask
    reference = json_data["data"]["reference"]
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'reference'

**Comment by Gilmour6415** [comment]
> I encountered a problem when running the same code as #3570. May I ask how to solve this problem? My problem is as follows: Traceback (most recent call last): File "/workspace/myragflow/test.py", line 15, in for ans in session.ask(question, stream=True): File "/root/anaconda3/envs/ragflow/lib/python3.12/site-packages/ragflow_sdk/modules/session.py", line 34, in ask reference = json_data["data"]["reference"] ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^ KeyError: 'reference'

see our solve at [https://github.com/infiniflow/ragflow/issues/3570#issuecomment-2550171714](url),  However, we also can not  completely solved the problem either.

**Pull request merged**
